#TODO: ?
feign:
  okhttp:
    enabled: true
server:
  port: 8081

spring:
  mvc:
    #TODO: ???? ??? ??.
    pathmatch:
      matching-strategy: ant_path_matcher
  #  config:
  #    activate:
  #      on-profile: "dev1"
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fintech?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: fintech
    password: fintech

  reactor:
    debug-agent:
      enabled: on

## ?? ??? application-{???}.yml ?????? ???.
## ?? ??? ???? .yml ??? ?? ?? ??? ????.
## ?? ?? ?? active-profile? {???}?? ?? ??.
## profile? ???? ?? ???? ??? ????? ????.